heat_template_version: 2013-05-23

description: A Heat Template

parameters:
  flavor:
    label: Server Size
    type: string
    default: 1 GB Performance

  image:
    label: Operating System
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr)

  server_name:
    label: Server Hostname
    type: string
    default: linux-server

resources:
  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  linux_server:
    type: "OS::Nova::Server"
    properties:
      key_name: { get_resource: ssh_key }
      flavor: { get_param: flavor }
      image: { get_param: image }
      name: { get_param: server_name }

outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }
    description: SSH Private Key

  server_ip:
    value: { get_attr: [linux_server, accessIPv4] }
    description: Server IP
